erikwiffin/0.30000000000000004

index.html
=> Add Elixir version

index.html
Add a note that PHP truncates the result on display based on a ini setting.
=> Add documentation for getting full representation from PHP

index.html
See https://www.python.org/dev/peps/pep-3105/ and https://docs.python.org/3.0/whatsnew/3.0.html#print-is-a-function
=> `print` is a statement in Python 2

index.html
Clojure handles rational numbers in a way similar to haskell.  Just giving it equal treatment here.
=> Clojure luv

index.html
the %f only prints the first 5 decimal places, you need at least 17 to see the difference.
=> C isn't immune to it either

index.html
Fixed a misplace break tag and added another Perl 5 example.
(aside ... if this stuff were all stored in JSON or something like that and then assembled into HTML it'd be less fiddly (but more work for you ;)).
=> A few more Perl tweaks

index.html
Adding Java Float example (previous only showed double, but you can also cast to float and get .3)
=> Adding Java Float Example

index.html
Ruby 2.1 and newer support rational numbers through syntax directly.
=> Add ruby rational syntax

index.html
(unformatted results - formatted results have identical accuracy)
=> Added Delphi XE5 and Turbo Pascal 7.0

index.html
adding iomanip, which is required for setprecision(17)
Adding a call into Lua that also prints 0.30000000000000004
=> Adding Call for Lua and iomanip for c++

index.html
I think this is formatted correctly but you might want to take a second look at it.
=> Addtheice rust patch

index.html
=> Add Postgres example

index.html
First example with binary floating point (IEEE-754) and second example
with decimal floating point (IEEE-754-2008).
=> Add examples in ABAP 

index.html
In swift, the result of (0.1 + 0.2) is also 0.30000000000000004. Add another example to avoid misunderstanding.
=> add another example for swift to avoid misunderstanding

_posts/2017-04-30-rust.md
=> Update Rust example to contemporary Rust

_posts/2017-04-30-csharp.md
Resolves #53 with an example of the decimal numeric type.
=> Adds C# decimal example

_posts/2017-04-30-javascript.md
Following https://github.com/erikwiffin/0.30000000000000004/issues/9#issuecomment-298282462
=> Add decimal.js as a note for JavaScript

_posts/2017-04-30-picolisp.md, _posts/2017-04-30-vbasic.md
- Added line breaks in MD
- Edited link to the module
=> Fix formatting

_posts/2017-04-30-crystal.md
This PR adds a `0.1 + 0.2` example for [The Crystal Programming Language](https://crystal-lang.org).
Crystal is a self-hosted programming language with friendly syntax, static type checking and modern stdlib. It compiles into efficient, easy-to-distribute native code.
=> Add Crystal

_posts/2017-04-30-elvish.md
=> Add elvish

_posts/2017-04-30-tcl.md
=> Tool Control Language (TCL) added

_posts/2017-04-30-sagemath.md
I hope I did this as intended :-)
=> add SageMath

_posts/2019-10-14-kotlin.md
Added example for Kotlin language.
@erikwiffin Just a heads up this PR is a part of my **hacktoberfest** challenge participation.
=> Add Kotlin

_posts/2019-10-14-kotlin.md
Semicolons are not mandatory. In fact, it is recommended to omit them whenever possible:
https://kotlinlang.org/docs/reference/coding-conventions.html#semicolons
=> Kotlin: remove semicolons

_posts/2017-04-30-julia.md
Hi, nice site and I love the domain :)
The Julia doc links were dead and now point to the new, updated docs.
=> Julia: Fix dead links to docs

_posts/2017-04-30-erlang.md
erlang only, as you ask https://github.com/erikwiffin/0.30000000000000004/pull/167
=> upd. erlang float precision example

_posts/2017-04-30-clojure.md
=> Remove duplicte text in clojure section

_posts/2020-09-16-fish.md
This PR adds a code example on how the fish-shell works with the floating point addition `0.1 + 0.2`.
=> Add Fish-Shell

_posts/2017-04-30-gforth.md
I would like to propose this change that adds 2 additional examples to help avoid assumption that gforth prints correct result.
NOTE that I'm not a forth programmer. I just did those tests for fun to verify result.
=> Add 2 more examples to gforth for clarification

_posts/2020-10-24-regina-rexx.md
Tested on REXX-Regina_3.9.1 on Linux
=> add Regina REXX

_posts/2020-10-24-regina-rexx.md
This was a string, output `.1+.2`
=> Fixed Regina
